-define(RECEIVER_ID_WITH_CONTENT, 1).
-define(RECEIVER_ID_WITHOUT_CONTENT, 2).

-define(NOT_FOUND_CONTENT_ID, 1).
-define(NON_PAYABLE_CONTENT_ID, 2).
-define(PENDING_PAYMENT_CONTENT_ID, 3).
-define(PAYMENT_SUCCESSFUL_CONTENT_ID, 4).
-define(ALREADY_PAID_CONTENT_ID, 5).
