openapi: 3.0.2

info:
  title: Consumer API
  version: '1.0'
  description: |
    # Consumer API: find content by receiver_id and pay if possible

servers:
  - url: http://localhost:{port}/{basePath}
    description: Development server
    variables:
      port:
        default: '8081'
      basePath:
        default: v1

components:
  schemas:
    Content:
      type: object
      required:
        - content_id
        - file_content
        - file_name
        - file_type
        - sender_id
        - receiver_id
        - is_payable
      properties:
        content_id:
          type: integer
        file_content:
          type: string
          format: binary
        file_name:
          type: string
        file_type:
          type: string
        sender_id:
          type: string
        receiver_id:
          type: string
        is_payable:
          type: boolean

paths:
  /{receiver_id}/content:
    get:
      summary: |
        Find files by receiver_id
      parameters:
        - name: receiver_id
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: |
            List of content
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Content"

  /content/{content_id}/pay:
    patch:
      summary: |
        Pay for payable content
      parameters:
        - name: content_id
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: |
            Success
          content:
            application/json:
              schema:
                type: object
                properties:
                  content_id:
                    type: string
