openapi: 3.0.2

info:
  title: Sender API
  version: '1.0'
  description: |
    # Sender API: accept a file in binary format with metadata:
      * sender id
      * file type
      * receiver id
      * is_payable

servers:
  - url: http://localhost:{port}/{basePath}
    description: Development server
    variables:
      port:
        default: '8080'
      basePath:
        default: v1

components:
  schemas:
    V1UploadPost:
      type: object
      required:
        - file_content
        - file_name
        - file_type
        - sender_id
        - receiver_id
        - is_payable
      properties:
        file_content:
          type: string
          format: binary
        file_name:
          type: string
        file_type:
          type: string
        sender_id:
          type: string
        receiver_id:
          type: string
        is_payable:
          type: boolean

paths:
  /upload:
    post:
      summary: |
        Upload a binary with metadata
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/V1UploadPost"
      responses:
        '201':
          description: |
            Success
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                  id:
                    type: string
        '200':
          description: |
            Already sent
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
